/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;


/**
 *
 * @author maihoa
 */
public class JList extends javax.swing.JFrame {

    /**
     * Creates new form JList
     */
    
    public JList() {
        initComponents();
        Update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        lstMH2 = new javax.swing.JList<>();
        btnSwitch1to2 = new javax.swing.JButton();
        btnSwitchAllFrom1to2 = new javax.swing.JButton();
        btnSwitch2to1 = new javax.swing.JButton();
        btnSwitchAllFrom2to1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMH1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));

        lstMH2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Bóng bàn" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstMH2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstMH2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstMH2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstMH2);

        btnSwitch1to2.setText(">");
        btnSwitch1to2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitch1to2ActionPerformed(evt);
            }
        });

        btnSwitchAllFrom1to2.setText(">>");
        btnSwitchAllFrom1to2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitchAllFrom1to2ActionPerformed(evt);
            }
        });

        btnSwitch2to1.setText("<");
        btnSwitch2to1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitch2to1ActionPerformed(evt);
            }
        });

        btnSwitchAllFrom2to1.setText("<<");
        btnSwitchAllFrom2to1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitchAllFrom2to1ActionPerformed(evt);
            }
        });

        jButton5.setText("+");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        lstMH1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstMH1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSwitch1to2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSwitchAllFrom1to2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSwitch2to1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSwitchAllFrom2to1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSwitch1to2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSwitchAllFrom1to2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSwitch2to1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSwitchAllFrom2to1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSwitch1to2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitch1to2ActionPerformed
        int stt = lstMH1.getSelectedIndex();
        if(stt != -1)
        {
        ListModel model = lstMH1.getModel();
        DSMHYeuThich.add(model.getElementAt(stt).toString());
        if(!DSMHTheThao.isEmpty())
        {
                DSMHTheThao.remove(stt); 
        }
        String[] up = DSMHTheThao.toArray(new String[0]);
        lstMH1.setListData(up);
        String[] addMH = DSMHYeuThich.toArray(new String[0]);
        lstMH2.setListData(addMH);
        }
        else
            JOptionPane.showMessageDialog( null,
                                     "Bạn chưa chọn giá trị"
                                             ,
                                     "Thông báo",
                                     JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_btnSwitch1to2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog("Nhập tên môn thể thao: ");
        DSMHTheThao.add(input);
        String[] up = DSMHTheThao.toArray(new String[0]);
        lstMH1.setListData(up);
    
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnSwitchAllFrom1to2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitchAllFrom1to2ActionPerformed
        ListModel model = lstMH1.getModel();
                       
        for (int i = 0; i < model.getSize(); i++) 
        {
            DSMHYeuThich.add(model.getElementAt(i).toString());
            if(!DSMHTheThao.isEmpty())
                DSMHTheThao.remove(i);
        }
        String[] up = DSMHTheThao.toArray(new String[0]);
        lstMH1.setListData(up);
        String[] addMH = DSMHYeuThich.toArray(new String[0]);
        lstMH2.setListData(addMH);
    }//GEN-LAST:event_btnSwitchAllFrom1to2ActionPerformed

    private void btnSwitch2to1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitch2to1ActionPerformed
        int stt = lstMH2.getSelectedIndex();
        if(stt != -1)
        {
        ListModel model = lstMH2.getModel();
        DSMHTheThao.add(model.getElementAt(stt).toString());    
        if(!DSMHYeuThich.isEmpty())
        {
                DSMHYeuThich.remove(stt);
               
        }
        String[] up = DSMHYeuThich.toArray(new String[0]);
        lstMH2.setListData(up);
        String[] addMH = DSMHTheThao.toArray(new String[0]);
        lstMH1.setListData(addMH);
        }
        else
            JOptionPane.showMessageDialog( null,
                                     "Bạn chưa chọn giá trị"
                                             ,
                                     "Thông báo",
                                     JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_btnSwitch2to1ActionPerformed

    private void btnSwitchAllFrom2to1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitchAllFrom2to1ActionPerformed
        ListModel model = lstMH2.getModel();
        for (int i = 0; i < model.getSize(); i++) 
        {
            DSMHTheThao.add(model.getElementAt(i).toString());
            if(!DSMHYeuThich.isEmpty())
                DSMHYeuThich.remove(i);
        }
        String[] up = DSMHYeuThich.toArray(new String[0]);
        lstMH2.setListData(up);
        String[] addMH = DSMHTheThao.toArray(new String[0]);
        lstMH1.setListData(addMH);
    }//GEN-LAST:event_btnSwitchAllFrom2to1ActionPerformed

    private void lstMH2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstMH2ValueChanged
      
    }//GEN-LAST:event_lstMH2ValueChanged
    
 
    
    private void Update()
    {
        ListModel model = lstMH1.getModel();
        for (int i = 0; i < model.getSize(); i++) {
            DSMHTheThao.add(model.getElementAt(i).toString());
        }
        model = lstMH2.getModel();
        for (int i = 0; i < model.getSize(); i++) {
            DSMHYeuThich.add(model.getElementAt(i).toString());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new JList().setVisible(true);
              
            }
        });
    }
    
    ArrayList<String> DSMHTheThao = new ArrayList<>();
    ArrayList<String> DSMHYeuThich = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSwitch1to2;
    private javax.swing.JButton btnSwitch2to1;
    private javax.swing.JButton btnSwitchAllFrom1to2;
    private javax.swing.JButton btnSwitchAllFrom2to1;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JList<String> lstMH1;
    private javax.swing.JList<String> lstMH2;
    // End of variables declaration//GEN-END:variables
}
